Repository boostcamp-2020/IssueTracker-35, pull requests merged in 2020-10, with the labels that each got.

#2 express 초기 설정
  .eslintrc.js
  .gitignore
  .vscode/settings.json
  server/main/app.js
  server/main/bin/www
  server/main/loaders/errorHandler.js
  server/main/loaders/express.js
  server/main/loaders/index.js
  server/main/routes/index.js
  server/main/utils/handler.js
  server/package-lock.json
  server/package.json
  server/webpack.config.js
Labels: backend

#3 front 개발 환경 설정
  .eslintrc.js
  .vscode/settings.json
  client/.eslintignore
  client/.eslintrc.js
  client/.prettierrc
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
  server/.eslintrc.js
  server/.prettierrc
  server/main/app.js
  server/main/loaders/errorHandler.js
  server/main/loaders/express.js
  server/main/loaders/index.js
  server/main/routes/index.js
  server/main/utils/handler.js
  server/package-lock.json
  server/package.json
  server/webpack.config.js
Labels: backend

#7 sequelize model 설정
  server/.eslintrc.js
  server/main/app.js
  server/main/bin/www
  server/main/loaders/errorHandler.js
  server/main/loaders/express.js
  server/main/loaders/index.js
  server/main/loaders/sequelize.js
  server/main/models/assignment.js
  server/main/models/index.js
  server/main/models/issue-label.js
  server/main/models/issue.js
  server/main/models/label.js
  server/main/models/milestone.js
  server/main/models/user.js
  server/main/routes/index.js
  server/main/utils/handler.js
  server/package-lock.json
  server/package.json
  server/test/seeds/issue.js
  server/test/services/issue.test.js
  server/webpack.config.js
Labels: backend

#8 Github 로그인 기능 구현
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.scss
  client/src/LoginContainer.js
  client/src/auth/github.js
  client/src/auth/index.js
  client/src/auth/login.js
  client/src/index.html
  client/src/index.js
  client/webpack.common.js
  client/webpack.dev.js
  server/main/bin/www
  server/main/controllers/user.js
  server/main/loaders/express.js
  server/main/passport/customStrategy.js
  server/main/passport/index.js
  server/main/routes/index.js
  server/main/routes/users.js
  server/main/utils/auth.js
  server/main/utils/handler.js
  server/package-lock.json
  server/package.json
Labels: backend, frontend

#9 Login page 레이아웃 작성
  client/src/App.scss
  client/src/LoginContainer.js
  client/src/auth/login.js
  client/src/auth/login.scss
Labels: frontend

#12 버전 0.0.1 배포
  .gitignore
  client/.eslintignore
  client/.eslintrc.js
  client/.prettierrc
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.scss
  client/src/auth/github.js
  client/src/auth/index.js
  client/src/auth/login.js
  client/src/auth/login.scss
  client/src/const/url.js
  client/src/index.html
  client/src/index.js
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
  server/.eslintrc.js
  server/.prettierrc
  server/main/app.js
  server/main/bin/www
  server/main/controllers/user.js
  server/main/loaders/errorHandler.js
  server/main/loaders/express.js
  server/main/loaders/index.js
  server/main/loaders/sequelize.js
  server/main/models/assignment.js
  server/main/models/index.js
  server/main/models/issue-label.js
  server/main/models/issue.js
  server/main/models/label.js
  server/main/models/milestone.js
  server/main/models/user.js
  server/main/passport/customStrategy.js
  server/main/passport/index.js
  server/main/routes/index.js
  server/main/routes/users.js
  server/main/utils/auth.js
  server/main/utils/handler.js
  server/package-lock.json
  server/package.json
  server/test/seeds/issue.js
  server/test/services/issue.test.js
Labels: ☁️ DEPLOY
